image: openjdk:11-jdk

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd ./hackathon-app/
  - export GRADLE_USER_HOME=`pwd`/.gradle

assemble:
  stage: build
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/
      - .gradle/

check:
  stage: test
  script: ./gradlew check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build/
      - .gradle/
